branch-defaults:
  dev:
    environment: udagram-jesusrodrc-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udacity-c2-restapi
  branch: null
  default_ec2_keyname: keypair
  default_platform: Node.js
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
